name: Pintos Checker
description: Check your implementation of PintOS
branding:
  icon: activity
  color: gray-dark
inputs:
  phase:
    description: "Phase to check"
    required: true
    default: "threads"
outputs:
  results:
    description: "results of checker"
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.phase }}
